{{- if and  .Values.clusterSecretStore.enabled .Values.clusterSecretStore.azurekv }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-cluster-secret-store
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: {{ required "A valid azure key vault value at .Values.clusterSecretStore.azurekv.vaultUrl is required" .Values.clusterSecretStore.azurekv.vaultUrl }}
      serviceAccountRef:
        name: {{ .Values.externalsecrets.serviceAccount.name }}
        namespace: {{ .Release.Namespace | quote }}
{{- end }}
