---
## https://cert-manager.io/docs/configuration/acme/dns01/azuredns/#configure-a-clusterissuer
## Applied locally , can be a part of cert manager local helm chart
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: ishansharma887@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          azureDNS:
            environment: AzurePublicCloud
            hostedZoneName: service.learndevops.in
            resourceGroupName: rg-argocd-cluster
            subscriptionID: "66f26fea-ff43-4f9a-bf6d-e2d18d696616"
            managedIdentity:
              clientID: "7e30f1dd-e2e9-41d9-ae7a-6fdc6356920f" ## from terraform output client_ids command
